//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexasBurger.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class BurgerContent
    {
        public int id { get; set; }
        public System.Guid burger_id { get; set; }
        public Nullable<int> burgerIngredient_id { get; set; }
    
        public virtual Burger Burger { get; set; }
        public virtual BurgerIngredient BurgerIngredient { get; set; }
    }
}
