//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexasBurger.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int id { get; set; }
        public int restaurant_id { get; set; }
        public int burger_ingredient_id { get; set; }
        public int quantity { get; set; }
    
        public virtual BurgerIngredient BurgerIngredient { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
