//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexasBurger.Persistence
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BurgerDBEntities : DbContext
    {
        public BurgerDBEntities()
            : base("name=BurgerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Burger> Burger { get; set; }
        public virtual DbSet<BurgerContent> BurgerContent { get; set; }
        public virtual DbSet<BurgerIngredient> BurgerIngredient { get; set; }
        public virtual DbSet<BurgerIngredientType> BurgerIngredientType { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderContent> OrderContent { get; set; }
        public virtual DbSet<Restaurant> Restaurant { get; set; }
    }
}
