//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO2API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> TransportMethodId { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<decimal> TotalCo2 { get; set; }
        public System.Data.Entity.Spatial.DbGeography StartLocation { get; set; }
        public System.Data.Entity.Spatial.DbGeography Endlocation { get; set; }
    
        public virtual TransportMethods TransportMethods { get; set; }
        public virtual User User { get; set; }
    }
}
