//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Co2CoopMainAPI3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int TripID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<int> transportMethod { get; set; }
        public Nullable<float> distance { get; set; }
        public Nullable<float> totalCo2 { get; set; }
        public System.Data.Entity.Spatial.DbGeography startLocation { get; set; }
        public System.Data.Entity.Spatial.DbGeography endlocation { get; set; }
    }
}
